import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/css/globals.css";
import { SupabaseSessionProvider } from '@/context/supabase-session-provider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wellness By Mark",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`flex justify-center items-center ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SupabaseSessionProvider>{children}</SupabaseSessionProvider>
      </body>
    </html>
  );
}
